Feature/317 training logic
fra-uas-project/softDsim pull request #357
Opened 2022-06-10 19:17 UTC by phimer

Delta ist noch nicht fertig

2022-06-10 19:18 UTC, phimer commented on backend/app/models/team.py
> +            delta = 1
Wie genau setzt sich das Delta zusammen? Konnte es aus der alten train() methode nicht so wirklich verstehen (ist als comment nochmal in Zeile 58)

2022-06-10 19:24 UTC, antonroesler commented on backend/app/models/team.py
> +            delta = 1
Das delta ist einfach die Differenz zwischen dem Mittelwert des throughputs aller member im Team und dem throughput des members den man sich gerade anschaut. Wenn das dann eine positive Zahl ist (wenn also der durchschnitt des teams besser ist las der Member x), dann wird der Member x besser (er bekommt also xp)

2022-06-10 19:26 UTC, antonroesler requested changes

2022-06-10 19:26 UTC, antonroesler commented on backend/app/models/team.py
> +        #         member.train(total_training_h, delta)
wenn wir die logik haben können wir es mergen

2022-06-11 06:21 UTC, phimer commented on backend/app/models/team.py
> +        #         member.train(total_training_h, delta)
Die restliche Training Logik hab ich aus der alten Methode übernommen, passt die noch?

2022-06-11 06:25 UTC, phimer commented
Und ist eine Erhöhung der Motivation um 10 prozentpunkte nicht zu hoch? Training kostet nur eine Stunde und erhöht Motivation dafür so stark?

2022-06-11 07:21 UTC, antonroesler commented on backend/app/models/team.py
> +        #         member.train(total_training_h, delta)
Ja sicher

2022-06-11 07:22 UTC, antonroesler commented
Ja muss man mal ausprobieren. Die Effekte sollen ja spürbar sein

2022-06-12 21:14 UTC, phimer commented
Ich habe die `team.training()` Methode rekursiv gebaut um Datenbank Zugriffe zu reduzieren (ohne Rekursion würde für jede Simulationsstunde in die Datenbank geschrieben werden, so nur einmal pro Simulationstag).
Vielleicht können wir das Prinzip auch für andere Schritte der `work()` Methode benutzen um die Simulationszeit ein bisschen zu verkürzen (ich glaube db calls brauchen bei uns den größten Anteil an Zeit).
Ich habe mir aber noch nicht angeschaut ob sich dieser Ansatz auch wirklich auf andere Schritte übertragen lässt.

2022-06-12 22:59 UTC, phimer commented
Ahh mir Ist grade ne viele einfachere Lösung eingefallen. Werde das morgen nochmal kurz überarbeiten.

2022-06-13 16:45 UTC, antonroesler requested changes

2022-06-13 16:45 UTC, antonroesler commented on backend/app/models/team.py
> +        solved_tasks = TaskStatus.solved(scenario.id)
Hier sollten wir CachedTasks benutzen, dann wird kein Request an die DB gesendet

2022-06-13 16:45 UTC, antonroesler commented on backend/app/models/team.py
> +        solved_tasks = TaskStatus.solved(scenario.id)
und es wird beim aufruf in line 122 ja sogar tasks übergeben.

2022-06-13 16:56 UTC, antonroesler approved these changes

2022-06-13 17:06 UTC, merged