feature: #383 end conditions for simulation fragments
fra-uas-project/softDsim pull request #390
Opened 2022-06-14 18:20 UTC by phimer

2022-06-15 17:16 UTC, antonroesler requested changes

2022-06-15 17:26 UTC, phimer commented on backend/app/src/simulation.py
>          raise RequestMembersException()
Hatte das glaube ich eingebaut, da irgendwas danach mit member gearbeitet hat und dann da ein error kam. Kann aber nochmal schauen.

2022-06-17 15:33 UTC, phimer commented
habe die exception raus genommen

2022-06-18 07:11 UTC, antonroesler approved these changes

2022-06-20 16:07 UTC, merged